### ISSUE TITLE
通过LDAP用户登录需要有一个默认的兜底

### ISSUE THREAD

**Issue by 9houhu** [infinilabs/console#114]
### 问题描述
目前配置了LDAP可以配置中指定的用户，把用户名一个的写出来，用户多并且用户有增减的时候，还要这样把用户都列出来，这个维护工作就是灾难

![Image](https://github.com/user-attachments/assets/6917b72f-1f1d-4148-893c-04671495459b)

建议新增一个兜底的用户权限配置，通过LDAP登录的用户有个默认权限

**Comment by luohoufu** [comment]
可在[快照版本](https://release.infinilabs.com/console/snapshot/)选择最新版本进行验证

- `default_roles` 使用示例：
```yaml
...
default_roles: [ "data-ro" ]
role_mapping:
  uid:
      ...
```
